# Generated by Django 3.1.4 on 2020-12-30 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guess.description')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guess.theme')),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guess.theme'),
        ),
    ]
